language: php
sudo: false

services:
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_DEPRECATIONS_HELPER=29

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_install:
  - composer self-update

install:
  - composer install --dev

before_script:
  - psql -c 'create database test;' -U postgres
  - ./bin/console doctrine:schema:create
  - ./bin/console doctrine:fixtures:load

script:
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
