version: "3.1"
services:
    postgresql:
      image: postgres:11.1-alpine
      container_name: app-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=username
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=database
      ports:
        - "5432:5432"
    webserver:
      image: nginx:alpine
      container_name: app-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
    php-fpm:
      build: .docker/php-fpm
      container_name: app-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - /application/vendor
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
